# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0004_auto_20171103_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='citizens',
        ),
        migrations.RemoveField(
            model_name='town',
            name='wall',
        ),
        migrations.RemoveField(
            model_name='town',
            name='wall_ap',
        ),
    ]
