# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0005_auto_20171103_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingtype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
