# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0006_auto_20171103_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='citizens',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='town',
            name='wall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='town',
            name='wall_ap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
