# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0008_auto_20171107_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='town_id',
            new_name='town',
        ),
    ]
