# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0009_auto_20171107_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='defence',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='defence',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
