# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0007_auto_20171103_1637'),
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='town_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='town.Town'),
        ),
    ]
