# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_character_town_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
