# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20171106_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='town_id',
            new_name='town',
        ),
    ]
